/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6_exti.h"
#include "lcd.h"

uint8_t FLAG = 1;
char str[] = "Interrupt Pin_9 GPIO_B";
void EXTI_IRQ_H(void);

//typedef struct
//{
//	volatile uint32_t ISERx[3];
//			 uint32_t RESERVED_2[29];
//	volatile uint32_t ICERx[3];
//	 	 	 uint32_t RESERVED_3[29];
//	volatile uint32_t ISPRx[3];
// 	 	 	 uint32_t RESERVED_4[29];
// 	volatile uint32_t ICPRx[3];
//}_REG_typedef;

int main(void)
{
	HAL_LCD_INIT();
	EXTI_PIN_CNFG_t PIN_CONFIG = EXTIB9;
	EXTI_CNFG_t EXTI_CONFIG;
	EXTI_CONFIG.PIN_CNFG = &PIN_CONFIG;
	EXTI_CONFIG.EXTIx_ENABLE_DISABLE = _EXTI_ENABLED;
	EXTI_CONFIG.Trigger_INTR_LINE = EXTI_TRIGGER_RISSING;
	EXTI_CONFIG.P_Func_EXTI_IRQ = EXTI_IRQ_H;
	MCAL_EXTI_GPIO_INIT(&EXTI_CONFIG);
	while(1)
	{
		if(FLAG)
		{
			HAL_LCD_SEND_COMMAND(DLCD_CLEAR_DISP);
			FLAG = 0;
		}
	}
}

void EXTI_IRQ_H(void)
{
	FLAG = 1;
	HAL_LCD_Write_STR(str);
	_delay_ms(1000);
}
