/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "datatypes_t.h"

#define RCC_BASE_ADD			0x40021000
#define SHIFT_RCC				0x18
#define PRCC_Base_Add       	*(vuint32_t *)(RCC_BASE_ADD + SHIFT_RCC)

#define GPIOA_BASE_ADD			0x40010800
#define SHIFT_POA_CRH			0x04
#define SHIFT_POA_ODR			0x0C
#define PPOA_CRH_REG         	(GPIOA_BASE_ADD + SHIFT_POA_CRH)
#define PPOA_ODR_REG          	(GPIOA_BASE_ADD + SHIFT_POA_ODR)

#define SBIT_APB2ENR 			(1<<2)

typedef union
{
	vuint32_t All_BITS;
	struct
	{
		vuint32_t Reserved_1:13;
		vuint32_t GPIO_ODR_REG:1;
		vuint32_t Reserved_2:6;
		vuint32_t GPIO_CRH_REG:4;
	}GPIO;
}GPIO_REG_t;

volatile GPIO_REG_t* GPIO_CRH_REG = (volatile GPIO_REG_t *)PPOA_CRH_REG;
volatile GPIO_REG_t* GPIO_ODR_REG = (volatile GPIO_REG_t *)PPOA_ODR_REG;

int main(void)
{

	PRCC_Base_Add |= SBIT_APB2ENR;
	GPIO_CRH_REG->GPIO.GPIO_CRH_REG = 0x02;

	while(1)
	{
		uint32_t i;
		GPIO_ODR_REG->GPIO.GPIO_ODR_REG = 1;
		for(i=0; i<500000; i++);
		GPIO_ODR_REG->GPIO.GPIO_ODR_REG = 0;
		for(i=0; i<500000; i++);
	}
	return 0;
}

