/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103x6_gpio.h"

void CLOCK_INIT(void);
void GPIO_INIT(void);
void delay(uint32_t T);

int main(void)
{
	//MCAL_GPIO_PIN_LOCK(GPIOB,GPIO_PIN_1);
	CLOCK_INIT();
	GPIO_INIT();
	while(1)
	{
		if(MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET)
		{
			while(MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET);
			MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_1);
		}
		if(MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN_13))
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_13);
			delay(50);
		}
	}
	return 0;
}

void CLOCK_INIT(void)
{
	//	Bit 2 IOPAEN: IO port A clock enable
	//	Set and cleared by software.
	//	0: IO port A clock disabled
	//	1: IO port A clock enabled
	GPIOA_CLOCK_ENABLE();


	//	Bit 3 IOPBEN: IO port B clock enable
	//	Set and cleared by software.
	//	0: IO port B clock disabled
	//	1: IO port B clock enabled
	GPIOB_CLOCK_ENABLE();
}

void GPIO_INIT(void)
{
	PIN_CFG_TypeDef GPIO_PIN_CFG;

	//Configure PORTA PIN 1 as Floating INPUT.
	GPIO_PIN_CFG.PIN_NUMBER = GPIO_PIN_1;
	GPIO_PIN_CFG.__PinMode = INPUT_MODE;
	GPIO_PIN_CFG.CNF_INPUT_CASE = Floating_input;
	GPIO_PIN_CFG.MODE_CASE = Input_mode;
	MCAL_GPIO_INIT(GPIOA, &GPIO_PIN_CFG);

	//Configure PORTA PIN 13 as Floating INPUT.
	GPIO_PIN_CFG.PIN_NUMBER = GPIO_PIN_13;
	MCAL_GPIO_INIT(GPIOA, &GPIO_PIN_CFG);

	//Configure PORTB PIN 1 as OUTPUT PUSH/PULL Mode.
	GPIO_PIN_CFG.PIN_NUMBER = GPIO_PIN_1;
	GPIO_PIN_CFG.__PinMode = OUTPUT_MODE;
	GPIO_PIN_CFG.CNF_OUTPUT_CASE = GPOutput_Push_pull;
	GPIO_PIN_CFG.MODE_CASE = Output_mode_max_speed_10MHz;
	MCAL_GPIO_INIT(GPIOB, &GPIO_PIN_CFG);

	//Configure PORTB PIN 13 as OUTPUT PUSH/PULL Mode.
	GPIO_PIN_CFG.PIN_NUMBER = GPIO_PIN_13;
	MCAL_GPIO_INIT(GPIOB, &GPIO_PIN_CFG);
}

void delay(uint32_t T)
{
	uint32_t i;
	for(i = 0; i < (T*2500); i++);
}

