/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103xx_uart.h"

USARTx_CFG uart_configgg;
uint16_t data_1;

void UART_Interrupt_AfterRx(void)
{
	MCAL_UART_Recieve(uart1, &data_1, PollingDisable);
	MCAL_UART_Transmit(uart1, &data_1, PollingEnable);
}

int main(void)
{
	uart_configgg.BaudRate = UARTx_BAUDRATE_9600;
	uart_configgg.WordLengh = WordLength_8;
	uart_configgg.StopBit = StopBit_1;
	uart_configgg.Parity = Parity_Disable;
	uart_configgg.TX_RX_Enable = UART_TxRxEnable;
	uart_configgg.HwFlowCtrl = CTS_RTS_Disable;
	uart_configgg.Interrupt_Condition = UARTx_IRQ_Rx_dataReady_Enable;
	uart_configgg.P_UART_IRQ = UART_Interrupt_AfterRx;
	MCAL_UART_INIT(uart1, &uart_configgg);
    while(1)
    {


    }
    return 0;
}
